### ISSUE TITLE
TZ info Bug ? 

### ISSUE THREAD

**Issue by BenouGui** [sillygoose/multisma2#3]
Good morning,
When I run multisma2 I get an error:
[multisma2] [ERROR] Unexpected exception caught: now() got an unexpected keyword argument 'tzinfo'

**Comment by sillygoose** [comment]
I am no longer maintaining this as I have moved to using Home Assistant for monitoring my three Sunnyboy inverters (and the power use), I recommend you check it out as it offers better integration and support.

About the error, I expect it is a package version issue but I can no longer test it since I sold off the Raspberry Pi servers I was using for multisma2.
